### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by mak163** [frealgagu/archlinux.webkitgtk#3]
I am a beginner Gento user and I need to build this package from source.
I get an error while compiling
If I understood correctly, you applied patches to the source code.
How to apply them correctly and how to compile this package from source code?

**Comment by frealgagu** [comment]
The last time I compile this thing was on december 7

https://github.com/frealgagu/archlinux.webkitgtk/releases/tag/3_2.4.11-26

Not sure if it's working right now, but looking in the AUR web page it looks like there is an error:

https://aur.archlinux.org/packages/webkitgtk#comment-863304

For these days it has been difficult for me to check it (and compiling this takes a lot of time).

I verify in gentoo if they have applied patches in some of the packages I maintain but it appears as no fix has been released for this one in particular LOL
